import { Product } from "./types";
export const fallbackProducts: Product[] = [
  {
    _id: "dual-wave-lipolysis",
    name: "980nm + 1470nm Lipolysis",
    slug: "980nm-1470nm-laser-lipolysis",
    category: "Machine + Training",
    price: 2999,
    summary:
      "Dual-wavelength diode laser lipolysis technology with professional hands-on training.",
    description:
      "A dual-wavelength diode laser lipolysis system for practitioners expanding into advanced aesthetic and body-contouring treatments. The two wavelengths do slightly different jobs: 980nm gives a deeper thermal effect, with coagulation and tissue contraction, while 1470nm is strongly absorbed by water-rich tissue, making it useful for controlled heating of more superficial tissue and for lipolysis. Used together, fat reduction and tightening can be approached in the same treatment. The course covers treatment protocols, safe use of the technology and how to introduce the service into your clinic with confidence.",
    applications: [
      "🔥 Skin tightening — heat can contract existing collagen fibres, which may give a tighter appearance",
      "🧬 Collagen stimulation — the healing and remodelling response can encourage new collagen formation over time",
      "✨ Improved skin laxity — often suited to mild or moderate laxity alongside small pockets of localised fat",
      "👩‍⚕️ Facial definition — commonly treated areas include the lower face, jawline and submental region",
      "🍑 Body contouring — abdomen, arms, thighs and other localised fat deposits, with tightening alongside fat reduction",
    ],
    features: [
      "980nm + 1470nm dual-wavelength technology",
      "Suitable for beauty therapists, medics and aesthetic practitioners",
      "Fully CE-marked machine",
      "One-year warranty",
      "Treatment fibres included",
      "Professional practical training",
      "Ongoing ZERYON support",
    ],
    included: [
      "Dual-wavelength diode laser lipolysis machine",
      "Professional treatment training",
      "Treatment protocol guidance",
      "Fibres and equipment onboarding",
      "Training dates: Monday 5 October or Monday 19 October",
    ],
    specifications: [
      { label: "Wavelengths", value: "980nm + 1470nm" },
      { label: "Machine + training", value: "£2,999 + VAT" },
      { label: "Training only", value: "£999 + VAT" },
      { label: "Warranty", value: "1 year" },
      { label: "Certification", value: "CE marked" },
      { label: "Alternative dates", value: "Available on request" },
      { label: "Course enquiries", value: "07736 317605" },
    ],
    image: "/Products/product%201.jpeg",
    featured: true,
  },
   {
    _id: "hifu-face-body",
    name: "22D Max Ultra",
    slug: "22d-max-ultra",
    category: "Machine + Training",
    price: 1750,
    summary:
      "22D Max Ultra multifunctional HIFU platform — facial lifting, body contouring, and intimate care training.",
    description:
      "The 22D Max Ultra is a multifunctional HIFU platform that combines a 13D HIFU facial handle for facial lifting and tightening, an 18D RS body handle for body contouring and RF, and a 30 RS private-care handle for intimate HIFU. It features multiple treatment depths including 1.5mm, 3.0mm, and 4.5mm for facial work, plus deeper cartridges for body treatments. The body system incorporates 6.78 MHz RF according to the manufacturer's specifications. This is considerably more than a basic HIFU machine — it's a comprehensive aesthetic platform for face, body, and intimate care.",
    applications: [
      "Facial lifting and tightening",
      "Body contouring and fat reduction",
      "Intimate HIFU treatments",
      "Collagen stimulation protocols",
      "SMAS layer tightening (1.5mm–4.5mm depths)",
      "Expanded aesthetics treatment menus",
    ],
    features: [
      "13D HIFU facial handle — facial lifting/tightening",
      "18D RS body handle — body contouring + 6.78 MHz RF",
      "30 RS private-care handle — intimate HIFU",
      "Multiple treatment depths (1.5mm, 3.0mm, 4.5mm facial, plus deeper body cartridges)",
      "CPD training with machine — £1,750",
      "Regulated Pro qualification training with machine — £2,499",
      "CPD training only — £3,000",
      "Fully CE-compliant machine",
      "One-year machine warranty",
      "Suitable for UK insurance providers subject to policy terms",
      "Continued ZERYON guidance and support",
    ],
    included: [
      "22D Max Ultra HIFU machine and setup guidance",
      "Professional face, body, and intimate care training",
      "Practical hands-on treatment experience",
      "CPD training with machine — £1,750 + VAT",
      "Regulated Pro qualification with machine — £2,499 + VAT",
      "CPD training only — £3,000 + VAT",
      "Training date: Monday 5 October or Monday 13 October",
      "Alternative dates available on request",
    ],
    specifications: [
      { label: "CPD training + machine", value: "£1,750 + VAT" },
      { label: "Regulated Pro qual + machine", value: "£2,499 + VAT" },
      { label: "CPD training only", value: "£3,000 + VAT" },
      { label: "Technology", value: "HIFU (13D facial / 18D RS body / 30 RS private-care)" },
      { label: "RF frequency", value: "6.78 MHz" },
      { label: "Facial depths", value: "1.5mm, 3.0mm, 4.5mm" },
      { label: "Body depths", value: "Deeper cartridges available" },
      { label: "Training time", value: "10am–4pm" },
      { label: "Warranty", value: "1 year" },
      { label: "Certification", value: "CE compliant" },
      { label: "Coverage", value: "Face + body + intimate care" },
      { label: "Alternative dates", value: "Available on request" },
    ],
    image: "/Products/product%202.jpeg",
    featured: true,
  },
  {
    _id: "zeryon-4-in-1",
    name: "ZERYON 4-in-1",
    slug: "zeryon-4-in-1",
    category: "Machine + Training",
    price: 4500,
    summary:
      "One versatile aesthetic system for four treatment opportunities, with comprehensive two-day training.",
    description:
      "Expand your clinic with one multi-technology system covering hair removal, tattoo removal, carbon facial and skin rejuvenation. The two-day ZERYON course gives you the practical knowledge to introduce all four treatments with confidence, creating more ways for clients to return and more value from one investment.",
    applications: [
      "Professional hair removal",
      "Tattoo removal",
      "Carbon facial treatments",
      "Skin rejuvenation",
    ],
    features: [
      "Four treatment pathways from one machine",
      "Two-day comprehensive practical training",
      "Advanced IPL, laser and RF technology",
      "Integrated cooling system",
      "CE-compliant machine",
      "One-year warranty",
      "Insurance-compatible subject to individual policy terms",
      "Ongoing ZERYON professional support",
    ],
    included: [
      "ZERYON multi-technology machine",
      "Two-day training across all four treatments",
      "Treatment protocols and practical guidance",
      "Machine onboarding and support access",
      "Training place secured after consultation",
    ],
    specifications: [
      { label: "Machine + 2-day training", value: "£4,500 + VAT" },
      { label: "Training only", value: "£1,200 + VAT" },
      { label: "Treatment pathways", value: "4" },
      { label: "Technology", value: "IPL + laser + RF" },
      { label: "Warranty", value: "1 year" },
      { label: "Certification", value: "CE compliant" },
      { label: "Support", value: "Ongoing" },
    ],
    image: "/Products/product%203.jpeg",
    featured: true,
  },
  {
    _id: "zeryon-pico",
    name: "ZERYON PICO",
    slug: "zeryon-pico",
    category: "Machine + Training",
    price: 1500,
    summary:
      "A compact professional system for tattoo, SPMU removal and carbon facial peel treatments.",
    description:
      "ZERYON PICO is designed for practitioners who want to enter the growing tattoo and semi-permanent make-up removal market without a large machine, a large treatment room or a major initial outlay. The one-day practical course covers treatment protocols, machine operation, safety and client considerations, with continued support after training.",
    applications: [
      "Professional tattoo removal",
      "Semi-permanent make-up removal",
      "Carbon facial peel treatments",
      "Compact and home-based clinic treatment menus",
    ],
    features: [
      "Compact clinic-friendly system",
      "One-day professional practical training",
      "Tattoo and SPMU removal protocols",
      "Carbon facial peel training",
      "Safety, contraindications and client considerations",
      "Machine operation guidance",
      "Ongoing ZERYON support after training",
    ],
    included: [
      "ZERYON PICO machine",
      "One-day professional training",
      "Tattoo removal training",
      "SPMU removal training",
      "Carbon facial peel training",
      "Practical treatment experience and protocols",
    ],
    specifications: [
      { label: "Machine + one-day training", value: "£1,500 + VAT" },
      { label: "Training only", value: "£599 + VAT" },
      { label: "Treatments", value: "Tattoo + SPMU + carbon peel" },
      { label: "Training duration", value: "1 day" },
      { label: "Format", value: "Compact tabletop system" },
      { label: "Course dates", value: "Available on request" },
      { label: "Support", value: "Ongoing" },
    ],
    image: "/Products/product%204.jpeg",
    featured: true,
  },
  {
    _id: "zeryon-co2",
    name: "ZERYON CO2 Laser",
    slug: "zeryon-co2-laser",
    category: "Machine + Training",
    price: 2200,
    summary:
      "Advanced CO2 laser technology for skin resurfacing, rejuvenation and clinic growth.",
    description:
      "A professional CO2 laser platform for practitioners who want to expand their treatment menu with skin resurfacing, rejuvenation, tightening and scar-improvement pathways. Training covers treatment options, safety and practical protocols so you can build additional revenue streams around your clients' skin goals.",
    applications: [
      "Skin resurfacing and rejuvenation",
      "Fine lines, wrinkles and skin tightening",
      "Uneven texture, acne and acne scarring",
      "Pigmentation and scar improvement",
      "Skin renewal treatments",
    ],
    features: [
      "One machine with multiple treatment opportunities",
      "Professional practitioner training",
      "CE-marked machine supplied",
      "Treatment protocols and client considerations",
      "Suitable for salons, clinics and aesthetic practitioners",
      "Support for expanding your treatment menu",
    ],
    included: [
      "ZERYON CO2 laser machine",
      "Professional training",
      "Treatment protocol guidance",
      "Safety and client consideration training",
      "Additional treatment pathway education",
    ],
    specifications: [
      { label: "Training + machine", value: "£2,200 + VAT" },
      { label: "Training only", value: "£699 + VAT" },
      { label: "Technology", value: "CO2 laser" },
      { label: "Applications", value: "Resurfacing, rejuvenation and renewal" },
      { label: "Certification", value: "CE marked" },
      { label: "Support", value: "Ongoing" },
    ],
    image: "/Products/product%205.jpeg",
    featured: true,
  },
  {
    _id: "z-lume",
    name: "ZERYON LUME",
    slug: "zeryon-lume",
    category: "Skin",
    price: 6995,
    summary:
      "A refined platform for professional skin-focused treatment menus.",
    description:
      "A considered technology platform for clinics introducing or expanding professional skin services. Full treatment claims and specifications are supplied after consultation.",
    applications: ["Professional skin protocols", "Clinic treatment menus"],
    features: [
      "Practitioner-led consultation",
      "Training pathway available",
      "Ongoing ZERYON support",
    ],
    included: [
      "Equipment onboarding",
      "Operational guidance",
      "Support access",
    ],
    specifications: [
      { label: "Configuration", value: "Confirmed during consultation" },
      { label: "Training", value: "Available" },
    ],
    featured: true,
  },
  {
    _id: "z-pulse",
    name: "ZERYON PULSE",
    slug: "zeryon-pulse",
    category: "Laser",
    price: 12995,
    summary:
      "Professional laser technology selected around the needs of your clinic.",
    description:
      "A professional laser system presented through a consultation-first process so suitability, qualification requirements and commercial fit can be properly discussed.",
    applications: ["Professional laser services", "Hair removal pathways"],
    features: [
      "Business-fit assessment",
      "Training options",
      "Post-purchase guidance",
    ],
    included: ["Machine onboarding", "Practitioner support", "Consultation"],
    specifications: [
      { label: "Technology", value: "Confirmed for selected configuration" },
      { label: "Warranty", value: "Confirmed before purchase" },
    ],
    featured: true,
  },
  {
    _id: "z-sculpt",
    name: "ZERYON SCULPT",
    slug: "zeryon-sculpt",
    category: "Body",
    price: 8495,
    summary:
      "A clinic-ready body technology platform with education built around it.",
    description:
      "Designed for practitioners exploring body treatment equipment without unnecessary outlay. ZERYON will help establish the right configuration for your services and experience.",
    applications: ["Body treatment menus", "Clinic expansion"],
    features: [
      "Configuration advice",
      "Practical education",
      "Ongoing support",
    ],
    included: [
      "Equipment introduction",
      "Training discussion",
      "Support access",
    ],
    specifications: [
      { label: "Applications", value: "Discussed at consultation" },
      { label: "Support", value: "Ongoing" },
    ],
    featured: true,
  },
];
